name: Java CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install secondstring and thirdparty
        run: mvn initialize
      - name: Build ${{ matrix.profile }} profile with Maven
        run: mvn --batch-mode ${{ matrix.profile }} install
